name: conditinal 

on: [push]

jobs:
  conditional:
    if: github.repository == 'dhruv-moradiya2/demo-for-host-ac'
    runs-on: ubuntu-latest
    steps:
      - name: "echo basic info"
        run: |
          echo "REF: $GITHUB_REF"
          echo "job Id: $GITHUB_JOB"

