name: depennd job

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: "my step 2 run before 1"
        run: echo "i am job2"

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "my step 1"
        run: echo "i am job1"
