name: check with cron

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: At every 2nd minute
        run: echo "date and time is $(date)"

