name: checking docker login

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
    check_docker:
        runs-on: ubuntu-latest
        # defaults:
        #   run:
        #     working-directory: .
        steps:
            - uses: actions/checkout@v4
            - name: check version and build file
              run: |
               docker --version
               docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }}
               docker build -t flask-app:latest .
               docker images 
               hostname -I
 
    build_image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build images and list image
              run:
               docker build -t flask-app:latest .
               docker images 
               hostname -I

               
    # check_login:
    #     runs-on: self-hosted
    #     steps:
    #         - name: check login
    #           run: |
    #             docker login -u ${{  secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }}
    
    
