name: checking docker login

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
    check_docker:
        runs-on: ubuntu-latest
        steps:
            - name: check version
              run: |
               docker --version
               docker login -u ${{  secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }}
               pwd
               ls
#              docker build -t flask-app:latest .
 
    check_login:
        runs-on: self-hosted
        steps:
            - name: check login
              run: |
                docker login -u ${{  secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }}
    
    
